version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: unless-stopped
    hostname: jenkins
    ports:
    # default port for jenkins: 8080
      - "8000:8080"
    volumes:
      - jenkins-vol:/var/jenkins_home
    networks:
      - jn-net

volumes:
  jenkins-vol:

networks:
  jn-net:
